apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lxcfs-admission-webhook
  namespace: lxcfs
spec:
  duration: 8760h
  renewBefore: 8000h
  subject:
    organizations:
      - demo.com
  commonName: lxcfs-admission-webhook.default
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
  - lxcfs-admission-webhook
  - lxcfs-admission-webhook.lxcfs
  - lxcfs-admission-webhook.lxcfs.svc
  - lxcfs-admission-webhook.lxcfs.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: lxcfs-admission-webhook
